// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jJWtXdMain5xS60WsJu2dTYTTMzmyow',
    appId: '1:961719847209:android:39de39ac330eb964c8cf38',
    messagingSenderId: '961719847209',
    projectId: 'idnyt-revamped-2023',
    storageBucket: 'idnyt-revamped-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM7IGoiajW5OlJ4gIRYV5dl8yzmUcmE2A',
    appId: '1:961719847209:ios:adc99b839fd5c1ccc8cf38',
    messagingSenderId: '961719847209',
    projectId: 'idnyt-revamped-2023',
    storageBucket: 'idnyt-revamped-2023.appspot.com',
    androidClientId: '961719847209-76bnkfrrpf0hoa194vs0hdeasc9qihtv.apps.googleusercontent.com',
    iosClientId: '961719847209-r8p6c7aqnia9d3vfqi1hiqpbb2lmjm11.apps.googleusercontent.com',
    iosBundleId: 'com.stevenson.idnytRevamped',
  );
}
